version: '3.9'

services:
  mongo:
    image: mongo:5
    restart: unless-stopped
    container_name: mongodb
    env_file: .env
    ports:
      - "27017:27017"
    networks:
      - pawdopt-private
    command: mongod
  

networks:
  pawdopt-private: