version: '3.9'

services:
  backend:
    image: pawdopt/backend:latest
    restart: unless-stopped
    container_name: pawdopt-backend
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3333:3333"
    networks:
      - pawdopt-private
  ml:
    image: pawdopt/ml:latest
    restart: unless-stopped
    container_name: pawdopt-ml
    build: 
      context: ./ml/
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "5000:5000"
    networks:
      - pawdopt-private

networks:
  pawdopt-private: