version: '3.9'

services:
  mongo:
    image: mongo:5
    restart: unless-stopped
    container_name: mongodb
    env_file: .env
    ports:
      - "27017:27017"
    networks:
      - pawdopt-private
    command: mongod
  keras:
    image: tensorflow/serving:latest-gpu
    restart: unless-stopped
    container_name: tensorflow-serving
    environment:
      - "MODEL_NAME=keras_model"
    ports:
      - "8501:8501"
    volumes:
      - type: bind
        source: ./ML/models/keras_model/
        target: /models/keras_model/
    networks:
      - pawdopt-private

  

networks:
  pawdopt-private: